<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ShipStation.Integration.Api</RootNamespace>
    <UserSecretsId>shipstation-integration-sample</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShipStation.Integration\ShipStation.Integration.csproj" />
  </ItemGroup>

</Project>
